<?php

return [
    'super_manager_cpf' => env('GROM_SUPER_MANAGER_CPF', '12347029835'),
    'default_password_prefix' => env('GROM_DEFAULT_PASSWORD_PREFIX', 'DDM'),

    'bootstrap_admin' => [
        'name' => env('GROM_BOOTSTRAP_ADMIN_NAME', 'Gestor Maximo GROM'),
        'username' => env('GROM_BOOTSTRAP_ADMIN_USERNAME', 'admin'),
        'cpf' => env('GROM_BOOTSTRAP_ADMIN_CPF', env('GROM_SUPER_MANAGER_CPF', '12347029835')),
        'email' => env('GROM_BOOTSTRAP_ADMIN_EMAIL', 'admin@grom.local'),
        'password' => env('GROM_BOOTSTRAP_ADMIN_PASSWORD'),
    ],

    'require_password_change' => env('GROM_REQUIRE_PASSWORD_CHANGE', false),

    'permissions' => [
        'dashboard.view' => ['module' => 'dashboard', 'name' => 'Visualizar dashboard'],
        'access.users.view' => ['module' => 'access', 'name' => 'Visualizar usuarios'],
        'access.users.create' => ['module' => 'access', 'name' => 'Criar usuarios'],
        'access.users.update' => ['module' => 'access', 'name' => 'Atualizar usuarios'],
        'access.users.toggle' => ['module' => 'access', 'name' => 'Ativar ou inativar usuarios'],
        'access.roles.view' => ['module' => 'access', 'name' => 'Visualizar papeis'],
        'access.roles.manage' => ['module' => 'access', 'name' => 'Gerenciar papeis'],
        'auditoria.view' => ['module' => 'auditoria', 'name' => 'Visualizar auditoria'],
        'produtividade.cartorios.view' => ['module' => 'produtividade', 'name' => 'Visualizar cartorios'],
        'produtividade.cartorios.manage' => ['module' => 'produtividade', 'name' => 'Gerenciar cartorios'],
        'produtividade.flagrantes.view' => ['module' => 'produtividade', 'name' => 'Visualizar flagrantes'],
        'produtividade.flagrantes.manage' => ['module' => 'produtividade', 'name' => 'Gerenciar flagrantes'],
        'produtividade.flagrantes.confirm' => ['module' => 'produtividade', 'name' => 'Confirmar flagrantes'],
        'produtividade.boletins.view' => ['module' => 'produtividade', 'name' => 'Visualizar boletins de ocorrencia'],
        'produtividade.boletins.manage' => ['module' => 'produtividade', 'name' => 'Gerenciar boletins de ocorrencia'],
        'produtividade.stats.view' => ['module' => 'produtividade', 'name' => 'Visualizar estatisticas'],
        'operacional.view' => ['module' => 'operacional', 'name' => 'Visualizar painel operacional'],
        'operacional.mandados.view' => ['module' => 'operacional', 'name' => 'Visualizar mandados de prisão'],
        'operacional.mandados.manage' => ['module' => 'operacional', 'name' => 'Gerenciar mandados de prisão'],
        'operacional.objetos.view' => ['module' => 'operacional', 'name' => 'Visualizar objetos apreendidos'],
        'operacional.objetos.manage' => ['module' => 'operacional', 'name' => 'Gerenciar objetos apreendidos'],
        'escalas.view' => ['module' => 'escalas', 'name' => 'Visualizar escalas e plantoes'],
        'escalas.manage' => ['module' => 'escalas', 'name' => 'Gerenciar escala mensal e plantoes'],
        'calendarios.view' => ['module' => 'calendarios', 'name' => 'Visualizar calendarios'],
        'backup.view' => ['module' => 'backup', 'name' => 'Visualizar backup'],
        'rh.view' => ['module' => 'rh', 'name' => 'Visualizar RH'],
        'rh.manage' => ['module' => 'rh', 'name' => 'Gerenciar RH'],
        'analise.view' => ['module' => 'analise', 'name' => 'Visualizar analise de dados'],
        'analise.manage' => ['module' => 'analise', 'name' => 'Gerenciar consolidacao'],
        'relatorios.emit' => ['module' => 'relatorios', 'name' => 'Emitir relatorios'],
        'calendarios.manage' => ['module' => 'calendarios', 'name' => 'Gerenciar calendarios'],
        'grom_ocr.view' => ['module' => 'grom_ocr', 'name' => 'Visualizar Grom OCR'],
        'grom_ocr.manage' => ['module' => 'grom_ocr', 'name' => 'Gerenciar Grom OCR'],
    ],

    'roles' => [
        'super_admin' => [
            'name' => 'Super Admin',
            'permissions' => ['*'],
        ],
        'administrador' => [
            'name' => 'Administrador',
            'permissions' => [
                'dashboard.view',
                'access.users.view',
                'access.users.update',
                'access.users.toggle',
                'access.roles.view',
                'access.roles.manage',
                'auditoria.view',
                'produtividade.cartorios.view',
                'produtividade.cartorios.manage',
                'produtividade.flagrantes.view',
                'produtividade.flagrantes.manage',
                'produtividade.flagrantes.confirm',
                'produtividade.boletins.view',
                'produtividade.boletins.manage',
                'produtividade.stats.view',
                'operacional.view',
                'operacional.mandados.view',
                'operacional.mandados.manage',
                'operacional.objetos.view',
                'operacional.objetos.manage',
                'escalas.view',
                'escalas.manage',
                'calendarios.view',
                'calendarios.manage',
                'backup.view',
                'rh.view',
                'auditoria.view',
                'analise.view',
                'analise.manage',
                'relatorios.emit',
            ],
        ],
        'gestor_cartorio' => [
            'name' => 'Gestor de Cartorio',
            'permissions' => [
                'dashboard.view',
                'produtividade.cartorios.view',
                'produtividade.cartorios.manage',
                'produtividade.flagrantes.view',
                'produtividade.flagrantes.manage',
                'produtividade.flagrantes.confirm',
                'produtividade.boletins.view',
                'produtividade.boletins.manage',
                'produtividade.stats.view',
                'operacional.view',
                'operacional.mandados.view',
                'operacional.mandados.manage',
                'operacional.objetos.view',
                'operacional.objetos.manage',
                'escalas.view',
                'escalas.manage',
                'calendarios.view',
                'calendarios.manage',
                'backup.view',
                'rh.view',
                'auditoria.view',
                'analise.view',
                'relatorios.emit',
            ],
        ],
        'operador' => [
            'name' => 'Operador',
            'permissions' => [
                'dashboard.view',
                'produtividade.cartorios.view',
                'produtividade.flagrantes.view',
                'produtividade.boletins.view',
                'produtividade.stats.view',
                'operacional.view',
                'operacional.mandados.view',
                'operacional.objetos.view',
                'escalas.view',
                'calendarios.view',
                'backup.view',
                'rh.view',
                'analise.view',
                'relatorios.emit',
            ],
        ],
        'consulta' => [
            'name' => 'Consulta',
            'permissions' => [
                'dashboard.view',
                'produtividade.cartorios.view',
                'produtividade.stats.view',
                'operacional.view',
                'operacional.mandados.view',
                'operacional.objetos.view',
                'escalas.view',
                'calendarios.view',
                'backup.view',
                'rh.view',
                'auditoria.view',
                'analise.view',
            ],
        ],
        'auditor' => [
            'name' => 'Auditor',
            'permissions' => [
                'dashboard.view',
                'access.users.view',
                'access.roles.view',
                'auditoria.view',
                'rh.view',
                'operacional.view',
                'operacional.mandados.view',
                'operacional.objetos.view',
                'escalas.view',
                'calendarios.view',
                'backup.view',
                'analise.view',
                'relatorios.emit',
            ],
        ],
    ],
];
